spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres.default.svc.cluster.local}:${DB_PORT:5432}/order_db
    username: order-service
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka.kafka.svc.cluster.local:9092}
    
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    topic:
      inventory-reserved-result: inventory-reserved-result-topic
      inventory-reserve-request: inventory-reserve-request-topic

server:
  port: 8002

grpc:
  server:
    port: 9002

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: healthz
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
